version: 2.1
orbs:
  node: circleci/node@2.0.0
  aws-s3: circleci/aws-s3@1.0.15
jobs:
  test-and-build:
    executor:
      name: node/default
      tag: '12.14.1'
    steps:
      - checkout
      - node/install-packages
      - run: npm run lint
      - run: npm run test:ci
      - run: npm run build
      - persist_to_workspace:
          root: ~/
          paths:
            - project/build
  deploy-to-s3:
    machine:
      - image: circleci/classic:latest
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          from: build
          to: 's3://my-cicd-example'
          overwrite: true # default is false

workflows:
  build-deploy:
    jobs:
      - test-and-build
      - deploy-to-s3:
          requires:
            - test-and-build
          filters:
            branches:
              only: master
