version: 2.1
orbs:
  node: circleci/node@2.0.0
jobs:
  test-and-build:
    executor:
      name: node/default
      tag: '12.14.1'
    steps:
      - checkout
      - node/install-packages
      - run: npm run lint
      - run: npm run test:ci
      - run: npm run build
workflows:
  test-and-build:
    jobs:
      - test-and-build
